name: Build and Push Docker Images to ECR

on:
  push:
    branches: [main]

env:
  ECR_REGISTRY: <YOUR_ECR_REGISTRY>
  AWS_REGION: <YOUR_AWS_REGION>

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and tag Docker images
      id: build-images
      run: |
        docker-compose build
        docker tag app:latest $ECR_REGISTRY/app:latest
        docker tag db:latest $ECR_REGISTRY/db:latest

    - name: Push Docker images to ECR
      id: push-images
      run: |
        docker push $ECR_REGISTRY/app:latest
        docker push $ECR_REGISTRY/db:latest
